import type { WeaponId, WeaponStats } from "./types";

export const weapons: { [K in WeaponId]: WeaponStats & { id: K } } = {
  fists: {
    id: "fists",
    label: "Fists",
    slot: "fists",
    kind: "unarmed",
    ammoType: "none",
    damage: 6,
    stun: 14,
    range: 0.75,
    attackMs: 450,
    noise: 4,
    lethal: false,
    magazineSize: 0,
    reloadMs: 0,
    recoil: 0,
    movingAccuracyPenalty: 0,
  },
  makeshift_knife: {
    id: "makeshift_knife",
    label: "Makeshift Knife",
    slot: "melee",
    kind: "melee",
    ammoType: "none",
    damage: 24,
    stun: 8,
    range: 0.85,
    attackMs: 360,
    noise: 8,
    lethal: true,
    magazineSize: 0,
    reloadMs: 0,
    recoil: 0,
    movingAccuracyPenalty: 0,
  },
  baton: {
    id: "baton",
    label: "Baton",
    slot: "melee",
    kind: "melee",
    ammoType: "none",
    damage: 14,
    stun: 34,
    range: 1,
    attackMs: 520,
    noise: 22,
    lethal: false,
    magazineSize: 0,
    reloadMs: 0,
    recoil: 0,
    movingAccuracyPenalty: 0,
  },
  bat: {
    id: "bat",
    label: "Bat",
    slot: "melee",
    kind: "melee",
    ammoType: "none",
    damage: 28,
    stun: 30,
    range: 1.15,
    attackMs: 680,
    noise: 30,
    lethal: false,
    magazineSize: 0,
    reloadMs: 0,
    recoil: 0,
    movingAccuracyPenalty: 0,
  },
  pipe: {
    id: "pipe",
    label: "Pipe",
    slot: "melee",
    kind: "melee",
    ammoType: "none",
    damage: 32,
    stun: 26,
    range: 1.1,
    attackMs: 640,
    noise: 32,
    lethal: true,
    magazineSize: 0,
    reloadMs: 0,
    recoil: 0,
    movingAccuracyPenalty: 0,
  },
  pistol: {
    id: "pistol",
    label: "Pistol",
    slot: "sidearm",
    kind: "gun",
    ammoType: "nine_mm",
    damage: 35,
    stun: 18,
    range: 8,
    attackMs: 360,
    noise: 70,
    lethal: true,
    magazineSize: 12,
    reloadMs: 1200,
    recoil: 0.16,
    movingAccuracyPenalty: 0.2,
  },
  smg: {
    id: "smg",
    label: "SMG",
    slot: "primary",
    kind: "gun",
    ammoType: "nine_mm",
    damage: 24,
    stun: 12,
    range: 7,
    attackMs: 110,
    noise: 78,
    lethal: true,
    magazineSize: 30,
    reloadMs: 1600,
    recoil: 0.28,
    movingAccuracyPenalty: 0.32,
  },
  shotgun: {
    id: "shotgun",
    label: "Shotgun",
    slot: "primary",
    kind: "gun",
    ammoType: "shells",
    damage: 70,
    stun: 40,
    range: 5,
    attackMs: 850,
    noise: 92,
    lethal: true,
    magazineSize: 6,
    reloadMs: 2200,
    recoil: 0.55,
    movingAccuracyPenalty: 0.38,
  },
  assault_rifle: {
    id: "assault_rifle",
    label: "Assault Rifle",
    slot: "primary",
    kind: "gun",
    ammoType: "rifle",
    damage: 42,
    stun: 18,
    range: 11,
    attackMs: 160,
    noise: 86,
    lethal: true,
    magazineSize: 30,
    reloadMs: 1900,
    recoil: 0.34,
    movingAccuracyPenalty: 0.35,
  },
  suppressed_pistol: {
    id: "suppressed_pistol",
    label: "Suppressed Pistol",
    slot: "sidearm",
    kind: "gun",
    ammoType: "nine_mm",
    damage: 28,
    stun: 14,
    range: 7,
    attackMs: 420,
    noise: 34,
    lethal: true,
    magazineSize: 10,
    reloadMs: 1300,
    recoil: 0.12,
    movingAccuracyPenalty: 0.16,
  },
};
